### ISSUE TITLE
502 Bad Gateway when attempting to Auth

### ISSUE THREAD

**Issue by mpking828** [justinjahn/nginx-auth#2]
Trying to setup 

Getting the following error:

```
Apr 27 12:44:38 oxidized nginx-auth[29143]: events.js:141
Apr 27 12:44:38 oxidized nginx-auth[29143]:       throw er; // Unhandled 'error' event
Apr 27 12:44:38 oxidized nginx-auth[29143]:       ^
Apr 27 12:44:38 oxidized nginx-auth[29143]: Error: getaddrinfo ENOTFOUND dccent1.uconnect.local dccent1.uconnect.local:389
Apr 27 12:44:38 oxidized nginx-auth[29143]:     at errnoException (dns.js:26:10)
Apr 27 12:44:38 oxidized nginx-auth[29143]:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
Apr 27 12:44:38 oxidized systemd[1]: nginx-auth.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 12:44:38 oxidized systemd[1]: nginx-auth.service: Unit entered failed state.
Apr 27 12:44:38 oxidized systemd[1]: nginx-auth.service: Failed with result 'exit-code'.
Apr 27 12:44:49 oxidized systemd[1]: nginx-auth.service: Service hold-off time over, scheduling restart.
Apr 27 12:44:49 oxidized systemd[1]: Stopped Web-based LDAP authentication using NGINX auth_request..
Apr 27 12:44:49 oxidized systemd[1]: Started Web-based LDAP authentication using NGINX auth_request..
Apr 27 12:44:49 oxidized nginx-auth[29168]: WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
Apr 27 12:44:49 oxidized nginx-auth[29168]: WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
Apr 27 12:44:49 oxidized nginx-auth[29168]: Warning: connect.session() MemoryStore is not
Apr 27 12:44:49 oxidized nginx-auth[29168]: designed for a production environment, as it will leak
Apr 27 12:44:49 oxidized nginx-auth[29168]: memory, and will not scale past a single process.
Apr 27 12:44:49 oxidized nginx-auth[29168]: Express server listening on port 3000

```

Checking the code, I found this in line 140 (and 240) in nginx-auth/app.js
```
    // Create the LDAP server and connect
    var ldap = ldapjs.createClient({ url: 'ldap://dccent1.uconnect.local' });
    ldap.connect();
```
Shouldn't that pull it from config file somehow (I don't see any allowed place to put it.)

**Comment by mpking828** [comment]
Changing that line in the code **appears** to fix it for me.   I don't have enough coding knowledge to make it into a variable in the config file however.

About 1 minuted after it worked, it did end up throwing another error (Same code area):

```
Apr 27 14:41:21 oxidized nginx-auth[29652]: events.js:141
Apr 27 14:41:21 oxidized nginx-auth[29652]:       throw er; // Unhandled 'error' event
Apr 27 14:41:21 oxidized nginx-auth[29652]:       ^
Apr 27 14:41:21 oxidized nginx-auth[29652]: Error: connect ETIMEDOUT 10.61.4.174:389
Apr 27 14:41:21 oxidized nginx-auth[29652]:     at Object.exports._errnoException (util.js:870:11)
Apr 27 14:41:21 oxidized nginx-auth[29652]:     at exports._exceptionWithHostPort (util.js:893:20)
Apr 27 14:41:21 oxidized nginx-auth[29652]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)
Apr 27 14:41:21 oxidized systemd[1]: nginx-auth.service: Main process exited, code=exited, status=1/FAILURE
Apr 27 14:41:21 oxidized systemd[1]: nginx-auth.service: Unit entered failed state.
Apr 27 14:41:21 oxidized systemd[1]: nginx-auth.service: Failed with result 'exit-code'.
Apr 27 14:41:31 oxidized systemd[1]: nginx-auth.service: Service hold-off time over, scheduling restart.

```

**Comment by justincjahn** [comment]
Whoops!  Looks like some test code made it into master-- sorry about that!  Commit f61dda3 fixes both of your issues:

* There is now a configuration entry for the LDAP URI to use.
* There's also some settings for TLS connections.
* The code will now catch connection errors and not crash.

Thanks!

**Comment by mpking828** [comment]
Thanks.

Git is pretty new to me.  How would I pull this update over the top of what I have.

something like:

sudo systemctl stop nginx-auth
sudo su - # Unless non-root users have access to the home directory.
cd /home/nginx-auth
sudo rm nginx-auth
sudo -u nginx-auth -H git clone https://github.com/justinjahn/nginx-auth.git

cd /home/nginx-auth/nginx-auth
sudo -u nginx-auth -H npm install

merge the config files (or type it over)

sydo systemctl start nginx-auth

**Comment by justincjahn** [comment]
The code is pretty easy to update:

    cd /home/nginx-auth
    sudo -u nginx-auth -H git pull

Since the config file has changed, you'll ether need to copy the `default.conf.dist` and re-configure or add the missing parts to your `default.conf` file.

Hope that helps!

P.S. GitHub has made a pretty neat interactive introduction to git: https://try.github.io/.
