### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by mpking828** [justinjahn/nginx-auth#4]
I'm not actually quite sure what I did to make this happen.  I only noticed it in the logs about 2 hours later.

I was playing with logging in, and logging out.  (Visting the /auth URL directly to allow logout)
```
Apr 28 11:58:24 oxidized nginx-auth[31824]: _http_outgoing.js:335
Apr 28 11:58:24 oxidized nginx-auth[31824]:     throw new Error('Can\'t set headers after they are sent.');
Apr 28 11:58:24 oxidized nginx-auth[31824]:     ^
Apr 28 11:58:24 oxidized nginx-auth[31824]: Error: Can't set headers after they are sent.
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at ServerResponse.header (/home/nginx-auth/nginx-auth/node_modules/express/lib/response.js:725:10)
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at ServerResponse.send (/home/nginx-auth/nginx-auth/node_modules/express/lib/response.js:170:12)
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at done (/home/nginx-auth/nginx-auth/node_modules/express/lib/response.js:962:10)
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at Immediate._onImmediate (/home/nginx-auth/nginx-auth/node_modules/express-handlebars/lib/utils.js:26:13)
Apr 28 11:58:24 oxidized nginx-auth[31824]:     at processImmediate [as _immediateCallback] (timers.js:383:17)
Apr 28 11:58:24 oxidized systemd[1]: nginx-auth.service: Main process exited, code=exited, status=1/FAILURE
Apr 28 11:58:24 oxidized systemd[1]: nginx-auth.service: Unit entered failed state.
Apr 28 11:58:24 oxidized systemd[1]: nginx-auth.service: Failed with result 'exit-code'.
Apr 28 11:58:34 oxidized systemd[1]: nginx-auth.service: Service hold-off time over, scheduling restart.
Apr 28 11:58:34 oxidized systemd[1]: Stopped Web-based LDAP authentication using NGINX auth_request..
Apr 28 11:58:34 oxidized systemd[1]: Started Web-based LDAP authentication using NGINX auth_request..
```

**Comment by mpking828** [comment]
I can't seem to reproduce this
